### ISSUE TITLE
Transcripts without polish

### ISSUE THREAD

**Issue by StevenBai97** [epi2me-labs/wf-isoforms#10]
Hi,

The reference-aided approach doesn't include the polish step. Will it affect the quality of annotation?

In addition, I have some difficulties to install nextflow and wf-isoforms by conda. Could I use softwares to identifies RNA isoforms independently as follow?
(1) cdna_classifier.py -r report.pdf -u unclassified.fq -w rescued.fq input.fq full-length.output.fq
(2) trim_isoseq_polyA -i full-length.output.fq
(3) minimap2 -ax splice -secondary=no -uf genome.fasta trim_fl.fq > mapped.sam
(4) samtools sort mapped.sam -o mapped.sorted.bam
(5) stringtie mapped.sorted.bam -L -G input.reference.gff -o output.gff
(6) gffcompare -R -C -K -r input.reference.gff output.gff

Thanks and best!

**Comment by nrhorner** [comment]
Hi Steven,

The de novo approach has an initial step of creating consensus transcript isoform sequences which the reads are then aligned to. The accuracy of these consensus sequences is improved by the polishing steps. 

For the reference-based approach, we already have good quality reference sequences to align to, so the polishing is not needed. 

Out workflows are not installable via conda. Please see https://labs.epi2me.io/wfquickstart

Neil

**Comment by StevenBai97** [comment]
> Hi Steven,
> 
> The de novo approach has an initial step of creating consensus transcript isoform sequences which the reads are then aligned to. The accuracy of these consensus sequences is improved by the polishing steps.
> 
> For the reference-based approach, we already have good quality reference sequences to align to, so the polishing is not needed.
> 
> Out workflows are not installable via conda. Please see https://labs.epi2me.io/wfquickstart
> 
> Neil

Thank you very much for your reply and suggestions. I will have a try.
