### ISSUE TITLE
error pulling docker image and minor issues

### ISSUE THREAD

**Issue by phpeters** [epi2me-labs/wf-isoforms#2]
Hej,

Thanks for developing this pipeline! I tried it but sadly, I ran into some issues, maybe you could have a look into it?
I'm using nextflow version 21.10.6 and singularity version 3.7.3

Thanks and best!
Philpp

* docker pull ontresearch/wf-isoforms
which results in 
Using default tag: latest
Error response from daemon: manifest for ontresearch/wf-isoforms:latest not found: manifest unknown: manifest unknown

same holds for wf-isoforms:v0.0.1 and for singularity. 

docker pull ontresearch/wf-isoforms:sha4a978c1a
works fine though, so I used this image. I'm not sure whether it is our system's settings or is the tag v0.0.1 just not set?

* "tuple(sample_id)" in main.nf -> process generate_fq_stats   should probably be "tuple val(sample_id)" ?
* "--threads n" with n>4 fails with e.g. "Process requirement exceed available CPUs -- req: 16; avail: 4" 
 I fixed this for me by commenting out the local executor in nextflow.config, since it uses all available cores by default ( https://www.nextflow.io/docs/latest/config.html#scope-executor )
* csvtk is not included in image sha4a978c1a, which makes process getVersions fail. Since it's not use anywhere I removed it from the process

**Comment by nrhorner** [comment]
Hi @phpeters 

I've released the version, v0.1.0, that should have been released previously. Sorry about that.  Please try the workflow out now.

**Comment by phpeters** [comment]
Hej,
Thanks for fixing this so quick! Pulling the image works fine now, the issue with the number of threads remains.
It's running right now, I'll let you know the outcome.
Thanks again and have a nice evening!
Philipp

**Comment by phpeters** [comment]
Hej,
The example runs through, thanks a lot! But I get no entries in the "Read mapping summary" table and an error message stating "ESC[31m[ERRO]ESC[0m EOF". 

I assume seqkit is missing an input stream, updating line 27 in [reference_assembly.nf](https://github.com/epi2me-labs/wf-isoforms/blob/master/reference_assembly.nf) from 

| samtools sort -@ ${params.threads} -o "${sample_id}_reads_aln_sorted.bam" - \
to 
| samtools sort -@ ${params.threads} - | tee "${sample_id}_reads_aln_sorted.bam" \

is fixing this for me. 
Besides this the issue can be closed. Thanks and best!
Philipp

**Comment by nrhorner** [comment]
Hi Philip,

Thanks. This is fixed now.

Neil
