### ISSUE TITLE
Output files for wf-isoforms

### ISSUE THREAD

**Issue by seongwoohan** [epi2me-labs/wf-isoforms#3]
According to the document, I expected to have a wf-isoforms-report.html, but I do not see any of them when following the instructions, as you can see in the screenshot below. Could you please take a look at this and let me know if I missed something?
![issue](https://user-images.githubusercontent.com/19489536/155239792-9ec4f4a8-b7f6-4dea-ab81-535e25d39f4d.png)

**Comment by nrhorner** [comment]
Hello,

Sorry for taking so long to respond. Could you please try the latest version (v0.1.1). And let me know if that doesn't fix your issue.

Neil

**Comment by cjw85** [comment]
Hi @seongwoohan 

Instructions for managing versions of our Nextflow workflows can be found here: https://labs.epi2me.io/managing-epi2me-labs-workflows-with-the-nextflow-command-line-interface
