### ISSUE TITLE
nextflow running error

### ISSUE THREAD

**Issue by yipukangda** [epi2me-labs/wf-isoforms#5]
Hi,

I download the latest v.0.1.1 version and run command as show below:
```
nextflow run main.nf --help
```
then get a error which shows:
```
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [hopeful_goldberg] - revision: dc2e1a1ca5
ERROR ~ expecting '}', found ',' @ line 276, column 35.
           path("wf-isoforms-*.html"), emit: report
                                     ^

1 error


 -- Check '.nextflow.log' file for details
```

**Comment by nrhorner** [comment]
Hi,

This is caused by using an old version of nextflow.  Could you please try with a recent nextflow release?

**Comment by MichealVo** [comment]
[custom.log](https://github.com/epi2me-labs/wf-isoforms/files/8374685/custom.log)
Thank you for your advice. I have attached the nextflow log file here. It was weird that the error only occurred as I used my .fastq file generated from my MinION mini-computer.
