### ISSUE TITLE
Error: denovo workflow (converting Us to Ts ?)

### ISSUE THREAD

**Issue by SomaG-PSN** [epi2me-labs/wf-isoforms#9]
Hi, I am trying to test denovo workflow for my dataset. This is using dRNAreads and I am getting the following error:

Error executing process > 'pipeline:denovo_assembly:make_batches (1)'
Caused by:
  Process `pipeline:denovo_assembly:make_batches (1)` terminated with an error exit status (134)
 
It calculates the batch size and num bases, but fails on running isONclust2.

echo "Batch size:$batch_size";
  echo "Num bases: $nr_bases";

  init_cls_options="--batch-size $batch_size --kmer-size 11 --window-size 15         --min-shared 5 --min-qual 7.0         --mapped-threshold 0.65 --aligned-threshold 0.2         --min-fraction 0.8 --min-prob-no-hits 0.1         -M -1 -P 500 -g 50         -c -150 -F 2 "
  mkdir -p sorted; isONclust2 sort $init_cls_options -v -o sorted 2B3_full_length_reads.fq;

Command exit status:
  134

Command output:
  Batch size:20628
  Num bases: 82512857

Command error:
  isONclust2 version: v2.3-e9da596
  Batches output directory: sorted
  Minimum batch size: 20628 kilobases
  Kmer size: 11
  Window size: 15
  Consensus period: 500
  Minimum cluster size for consensus: 50
  Maximum cluster size for consensus: -150
  Minimum average quality: 7
  Minimum shared minimizers: 5
  Minimum fraction of top minimizer hit: 0.8
  Mapping threshold: 0.65
  Alignment threshold: 0.2
  Minimum probability no hit: 0.1
  Minimum cluster size in left batches: 2
  Debug output: off
  Warning: reusing existing output directory: sorted
  Parsed 506313 sequences.
  Finished sorting sequences.
  Sorted sequences written to: sorted/sorted_reads.fastq
  Scorer written to: sorted/scores.tsv
r executing process > 'pipeline:denovo_assembly:make_batches (1)'

Caused by:
  Process `pipeline:denovo_assembly:make_batches (1)` terminated with an error exit status (134)

  Preparing batches:
  terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
  .command.sh: line 19: 70223 Aborted                 isONclust2 sort $init_cls_options -v -o sorted 2B3_full_length_reads.fq

I had seen a similar issue here (https://github.com/epi2me-labs/wf-isoforms/issues/7) and it was suggested on isONclust site (https://github.com/nanoporetech/isONclust2/issues/4#issue-678931960) that we should convert all Us to Ts in the fastq file. 
Is that true? Can we somehow change the option to consider Us ?

**Comment by nrhorner** [comment]
Hi,

We are not currently supporting the experimental de novo pipeline with dRNA reads at the moment. Apologies for the inconvenience. I will let you know when it gets added.

**Comment by SomaG-PSN** [comment]
Thank you for the quick update!!. I will stay tuned.
